"""add notifications

Revision ID: 0e469321b805
Revises: 7b6ea6689e2a
Create Date: 2026-10-07 17:39:59.123882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e469321b805'
down_revision: Union[str, Sequence[str], None] = '7b6ea6689e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the notifications table.

    Startup runs ``create_all`` before migrations, so the table may already
    exist on a fresh database; skip it then, as the Fleet revision does.
    """
    if "notifications" in sa.inspect(op.get_bind()).get_table_names():
        return
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), server_default='turn_end', nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('session_name', sa.String(), nullable=False),
    sa.Column('pane_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_project_id'), ['project_id'], unique=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_project_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
