"""fleet lead: questions, Lead bookkeeping, task-less Lead attempts

Revision ID: 308d6ecba937
Revises: 62441d02bf95
Create Date: 2026-09-23 13:24:26.145075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308d6ecba937'
down_revision: Union[str, Sequence[str], None] = '62441d02bf95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_MISSION_COLUMNS = [
    sa.Column('lead_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('lead_restarts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lead_cursor_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lead_nudged_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('plan_ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_notes', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
]


def upgrade() -> None:
    """Upgrade schema.

    Guarded throughout: startup's create_all may already have created the new
    table and columns before migrations run.
    """
    bind = op.get_bind()
    if "fleet_questions" not in sa.inspect(bind).get_table_names():
        op.create_table('fleet_questions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('mission_id', sa.String(), nullable=False),
        sa.Column('attempt_id', sa.String(), nullable=True),
        sa.Column('fleet_task_id', sa.String(), nullable=True),
        sa.Column('asked_by', sa.String(), nullable=False),
        sa.Column('routed_to', sa.String(), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('options_json', sa.Text(), server_default='[]', nullable=False),
        sa.Column('default_answer', sa.Text(), nullable=True),
        sa.Column('why', sa.Text(), nullable=True),
        sa.Column('human_reserved', sa.Boolean(), server_default='0', nullable=False),
        sa.Column('state', sa.String(), server_default='open', nullable=False),
        sa.Column('answer', sa.Text(), nullable=True),
        sa.Column('answered_by', sa.String(), nullable=True),
        sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("routed_to IN ('lead', 'human')", name='ck_fleet_questions_routed_to'),
        sa.CheckConstraint("state IN ('open', 'answered', 'defaulted', 'cancelled')", name='ck_fleet_questions_state'),
        sa.ForeignKeyConstraint(['attempt_id'], ['fleet_attempts.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['fleet_task_id'], ['fleet_tasks.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['mission_id'], ['fleet_missions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    indexes = {i["name"] for i in sa.inspect(bind).get_indexes("fleet_questions")}
    for name, column in (("ix_fleet_questions_mission_id", "mission_id"), ("ix_fleet_questions_state", "state")):
        if name not in indexes:
            op.create_index(name, "fleet_questions", [column], unique=False)
    task_column = next(c for c in sa.inspect(bind).get_columns("fleet_attempts") if c["name"] == "fleet_task_id")
    if not task_column["nullable"]:
        with op.batch_alter_table("fleet_attempts", schema=None) as batch_op:
            batch_op.alter_column("fleet_task_id", existing_type=sa.String(), nullable=True)
    existing = {c["name"] for c in sa.inspect(bind).get_columns("fleet_missions")}
    missing = [column for column in _MISSION_COLUMNS if column.name not in existing]
    if missing:
        with op.batch_alter_table("fleet_missions", schema=None) as batch_op:
            for column in missing:
                batch_op.add_column(column)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_missions', schema=None) as batch_op:
        batch_op.drop_column('report')
        batch_op.drop_column('plan_notes')
        batch_op.drop_column('plan_ready_at')
        batch_op.drop_column('lead_nudged_seq')
        batch_op.drop_column('lead_cursor_seq')
        batch_op.drop_column('lead_restarts')
        batch_op.drop_column('lead_enabled')

    with op.batch_alter_table('fleet_attempts', schema=None) as batch_op:
        batch_op.alter_column('fleet_task_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('fleet_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_questions_state'))
        batch_op.drop_index(batch_op.f('ix_fleet_questions_mission_id'))

    op.drop_table('fleet_questions')
    # ### end Alembic commands ###
