"""fleet triggers and continuous work

Revision ID: 3f7e985b6a91
Revises: b0bd84338cc5
Create Date: 2026-09-23 20:44:24.468436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7e985b6a91'
down_revision: Union[str, Sequence[str], None] = 'b0bd84338cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. Guarded: startup's create_all may have created these already."""
    bind = op.get_bind()
    tables = set(sa.inspect(bind).get_table_names())
    if 'fleet_triggers' not in tables:
        _create_triggers()
    if 'fleet_trigger_items' not in tables:
        _create_trigger_items()
    attempt_columns = {c['name'] for c in sa.inspect(bind).get_columns('fleet_attempts')}
    if 'review_cost_usd' not in attempt_columns:
        with op.batch_alter_table('fleet_attempts', schema=None) as batch_op:
            batch_op.add_column(sa.Column('review_cost_usd', sa.Float(), server_default='0', nullable=False))
    columns = {c['name'] for c in sa.inspect(bind).get_columns('fleet_missions')}
    indexes = {i['name'] for i in sa.inspect(bind).get_indexes('fleet_missions')}
    with op.batch_alter_table('fleet_missions', schema=None) as batch_op:
        if 'trigger_id' not in columns:
            batch_op.add_column(sa.Column('trigger_id', sa.String(), nullable=True))
        if 'ix_fleet_missions_trigger_id' not in indexes:
            batch_op.create_index(batch_op.f('ix_fleet_missions_trigger_id'), ['trigger_id'], unique=False)


def _create_triggers() -> None:
    op.create_table('fleet_triggers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('config_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('interval_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('autonomy_level', sa.Integer(), server_default='3', nullable=False),
    sa.Column('max_open_missions', sa.Integer(), server_default='1', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('schedule', 'github_issues', 'ci_failure', 'todos')", name='ck_fleet_triggers_kind'),
    sa.CheckConstraint('autonomy_level BETWEEN 1 AND 4', name='ck_fleet_triggers_autonomy_level'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleet_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleet_triggers_project_id'), ['project_id'], unique=False)


def _create_trigger_items() -> None:
    op.create_table('fleet_trigger_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trigger_id', sa.String(), nullable=False),
    sa.Column('external_key', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trigger_id'], ['fleet_triggers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trigger_id', 'external_key', name='uq_fleet_trigger_items_key')
    )
    with op.batch_alter_table('fleet_trigger_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleet_trigger_items_trigger_id'), ['trigger_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('fleet_attempts', schema=None) as batch_op:
        batch_op.drop_column('review_cost_usd')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_missions_trigger_id'))
        batch_op.drop_column('trigger_id')

    with op.batch_alter_table('fleet_trigger_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_trigger_items_trigger_id'))

    op.drop_table('fleet_trigger_items')
    with op.batch_alter_table('fleet_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_triggers_project_id'))

    op.drop_table('fleet_triggers')
    # ### end Alembic commands ###
