"""fleet control surface: take-over and shipping state

Revision ID: 55f6afddd80f
Revises: 308d6ecba937
Create Date: 2026-09-23 13:59:45.173595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f6afddd80f'
down_revision: Union[str, Sequence[str], None] = '308d6ecba937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ADDED_COLUMNS = {
    'fleet_attempts': [
        sa.Column('human_control', sa.Boolean(), server_default='0', nullable=False),
        sa.Column('held_messages', sa.Text(), server_default='[]', nullable=False),
    ],
    'fleet_missions': [
        sa.Column('shipped_sha', sa.String(), nullable=True),
        sa.Column('shipped_to', sa.String(), nullable=True),
    ],
}


def upgrade() -> None:
    """Upgrade schema. Guarded: create_all may already have added these columns."""
    for table, columns in _ADDED_COLUMNS.items():
        existing = {c["name"] for c in sa.inspect(op.get_bind()).get_columns(table)}
        missing = [column for column in columns if column.name not in existing]
        if missing:
            with op.batch_alter_table(table, schema=None) as batch_op:
                for column in missing:
                    batch_op.add_column(column)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_missions', schema=None) as batch_op:
        batch_op.drop_column('shipped_to')
        batch_op.drop_column('shipped_sha')

    with op.batch_alter_table('fleet_attempts', schema=None) as batch_op:
        batch_op.drop_column('held_messages')
        batch_op.drop_column('human_control')

    # ### end Alembic commands ###
