"""fleet done gate: report, verification and landing state on attempts

Revision ID: 597c46eb616d
Revises: f3537bbb1a21
Create Date: 2026-09-23 12:04:31.169194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597c46eb616d'
down_revision: Union[str, Sequence[str], None] = 'f3537bbb1a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_COLUMNS = [
    sa.Column('gate_state', sa.String(), server_default='none', nullable=False),
    sa.Column('gate_blocks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fix_rounds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('report_outcome', sa.String(), nullable=True),
    sa.Column('report_summary', sa.Text(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verify_log', sa.Text(), nullable=True),
    sa.Column('landed_sha', sa.String(), nullable=True),
]


def upgrade() -> None:
    """Upgrade schema.

    Guarded per column: startup's create_all may already have created
    fleet_attempts with these columns before migrations run.
    """
    existing = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("fleet_attempts")}
    missing = [column for column in _COLUMNS if column.name not in existing]
    if missing:
        with op.batch_alter_table("fleet_attempts", schema=None) as batch_op:
            for column in missing:
                batch_op.add_column(column)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_attempts', schema=None) as batch_op:
        batch_op.drop_column('landed_sha')
        batch_op.drop_column('verify_log')
        batch_op.drop_column('reported_at')
        batch_op.drop_column('report_json')
        batch_op.drop_column('report_summary')
        batch_op.drop_column('report_outcome')
        batch_op.drop_column('fix_rounds')
        batch_op.drop_column('gate_blocks')
        batch_op.drop_column('gate_state')

    # ### end Alembic commands ###
