"""fleet scheduling: retries, refinery, controls, mission budget

Revision ID: 62441d02bf95
Revises: 597c46eb616d
Create Date: 2026-09-23 12:17:51.206085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62441d02bf95'
down_revision: Union[str, Sequence[str], None] = '597c46eb616d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ADDED_COLUMNS = {
    'fleet_attempts': [
        sa.Column('purpose', sa.String(), server_default='task', nullable=False),
        sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    ],
    'fleet_missions': [
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('state_reason', sa.Text(), nullable=True),
    ],
    'fleet_tasks': [
        sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
        sa.Column('failure_kind', sa.String(), nullable=True),
        sa.Column('blocked_reason', sa.Text(), nullable=True),
    ],
}


def upgrade() -> None:
    """Upgrade schema.

    Guarded: startup's create_all may already have created these tables and
    columns before migrations run.
    """
    inspector = sa.inspect(op.get_bind())
    if "fleet_controls" not in inspector.get_table_names():
        op.create_table('fleet_controls',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('key')
        )
    for table, columns in _ADDED_COLUMNS.items():
        existing = {c["name"] for c in sa.inspect(op.get_bind()).get_columns(table)}
        missing = [column for column in columns if column.name not in existing]
        if missing:
            with op.batch_alter_table(table, schema=None) as batch_op:
                for column in missing:
                    batch_op.add_column(column)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_tasks', schema=None) as batch_op:
        batch_op.drop_column('blocked_reason')
        batch_op.drop_column('failure_kind')
        batch_op.drop_column('failure_count')

    with op.batch_alter_table('fleet_missions', schema=None) as batch_op:
        batch_op.drop_column('state_reason')
        batch_op.drop_column('started_at')

    with op.batch_alter_table('fleet_attempts', schema=None) as batch_op:
        batch_op.drop_column('released_at')
        batch_op.drop_column('settled_at')
        batch_op.drop_column('purpose')

    op.drop_table('fleet_controls')
    # ### end Alembic commands ###
