"""remove session automation and learned todo planning

Revision ID: 637eb26d3286
Revises: 9324cf29e61e
Create Date: 2026-10-07 16:03:47.913286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637eb26d3286'
down_revision: Union[str, Sequence[str], None] = '9324cf29e61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop Learn/Active session automation and learned Todo planning.

    Tasks are kept, including those a proposal created; only the link back to
    the proposal goes. Children are dropped before the tables they reference.
    """
    tables = set(sa.inspect(op.get_bind()).get_table_names())
    for table in (
        "task_planning_events",
        "task_proposals",
        "session_automation_events",
        "session_automations",
        "project_direction_events",
        "project_direction_contracts",
    ):
        if table in tables:
            op.drop_table(table)
    for table, column, index in (
        ("task_workflows", "automation_owner_id", "ix_task_workflows_automation_owner_id"),
        ("tasks", "source_proposal_id", "ix_tasks_source_proposal_id"),
    ):
        inspector = sa.inspect(op.get_bind())
        if column not in {item["name"] for item in inspector.get_columns(table)}:
            continue
        indexes = {item["name"] for item in inspector.get_indexes(table)}
        with op.batch_alter_table(table, schema=None) as batch_op:
            if index in indexes:
                batch_op.drop_index(index)
            batch_op.drop_column(column)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_proposal_id', sa.VARCHAR(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_source_proposal_id'), ['source_proposal_id'], unique=1)

    with op.batch_alter_table('task_workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automation_owner_id', sa.VARCHAR(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_workflows_automation_owner_id'), ['automation_owner_id'], unique=False)

    op.create_table('project_direction_contracts',
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('problem', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('target_users', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('vision', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('value_proposition', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('current_goal', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('desired_outcome', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('success_metrics_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('non_goals_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('boundaries_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('assumptions_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('source_refs_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('task_ids_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('methodology', sa.VARCHAR(), server_default=sa.text("'bmad-method'"), nullable=False),
    sa.Column('methodology_version', sa.VARCHAR(), nullable=False),
    sa.Column('methodology_sha', sa.VARCHAR(), nullable=False),
    sa.Column('methodology_url', sa.TEXT(), nullable=False),
    sa.Column('revision', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('approved_revision', sa.INTEGER(), nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'completed', 'cancelled', 'superseded')", name=op.f('ck_project_direction_contract_status')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('task_planning_events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('proposal_id', sa.VARCHAR(), nullable=True),
    sa.Column('proposal_revision', sa.INTEGER(), nullable=False),
    sa.Column('kind', sa.VARCHAR(), nullable=False),
    sa.Column('actor', sa.VARCHAR(), nullable=False),
    sa.Column('source_event_key', sa.VARCHAR(), nullable=False),
    sa.Column('snapshot_json', sa.TEXT(), nullable=False),
    sa.Column('snapshot_hash', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('provenance_sequence', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("kind IN ('proposed', 'updated', 'superseded', 'approved', 'rejected')", name=op.f('ck_task_planning_events_kind')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['task_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_planning_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_planning_events_proposal_sequence'), ['proposal_id', 'provenance_sequence'], unique=1)
        batch_op.create_index(batch_op.f('ix_task_planning_events_proposal_actor_created'), ['proposal_id', 'actor', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_planning_events_project_created'), ['project_id', 'created_at'], unique=False)

    op.create_table('session_automation_events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('automation_id', sa.VARCHAR(), nullable=False),
    sa.Column('event_key', sa.VARCHAR(), nullable=False),
    sa.Column('kind', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('agent_session_id', sa.VARCHAR(), nullable=True),
    sa.Column('origin', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('decision_json', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_code', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('source_event_key', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_hash', sa.VARCHAR(), nullable=True),
    sa.Column('snapshot_hash', sa.VARCHAR(), nullable=True),
    sa.Column('policy_version', sa.VARCHAR(), nullable=True),
    sa.Column('tmux_server_id', sa.VARCHAR(), nullable=True),
    sa.Column('tmux_session_id', sa.VARCHAR(), nullable=True),
    sa.Column('pane_id', sa.VARCHAR(), nullable=True),
    sa.Column('generation', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'processed', 'cancelled', 'failed')", name=op.f('ck_session_automation_events_status')),
    sa.ForeignKeyConstraint(['automation_id'], ['session_automations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_automation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_session_automation_events_event_key'), ['event_key'], unique=1)
        batch_op.create_index(batch_op.f('ix_session_automation_events_pending'), ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_automation_events_automation'), ['automation_id', 'created_at'], unique=False)

    op.create_table('session_automations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('session_name', sa.VARCHAR(), nullable=False),
    sa.Column('tmux_server_id', sa.VARCHAR(), nullable=False),
    sa.Column('tmux_session_id', sa.VARCHAR(), nullable=False),
    sa.Column('pane_id', sa.VARCHAR(), nullable=False),
    sa.Column('pane_pid', sa.INTEGER(), nullable=False),
    sa.Column('pane_process_start_ticks', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('mode', sa.VARCHAR(), server_default=sa.text("'off'"), nullable=False),
    sa.Column('state', sa.VARCHAR(), server_default=sa.text("'idle'"), nullable=False),
    sa.Column('generation', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('goal', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('max_turns', sa.INTEGER(), server_default=sa.text("'8'"), nullable=False),
    sa.Column('max_minutes', sa.INTEGER(), server_default=sa.text("'30'"), nullable=False),
    sa.Column('max_failures', sa.INTEGER(), server_default=sa.text("'3'"), nullable=False),
    sa.Column('send_delay_seconds', sa.INTEGER(), server_default=sa.text("'5'"), nullable=False),
    sa.Column('turns_used', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('consecutive_failures', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('activated_at', sa.DATETIME(), nullable=True),
    sa.Column('pending_prompt', sa.TEXT(), nullable=True),
    sa.Column('pending_prompt_hash', sa.VARCHAR(), nullable=True),
    sa.Column('pending_send_at', sa.DATETIME(), nullable=True),
    sa.Column('last_decision', sa.VARCHAR(), nullable=True),
    sa.Column('last_reason', sa.TEXT(), nullable=True),
    sa.Column('last_error', sa.VARCHAR(), nullable=True),
    sa.Column('planner_warning', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('pending_prompt_fingerprint', sa.VARCHAR(), nullable=True),
    sa.Column('pending_source_event_key', sa.VARCHAR(), nullable=True),
    sa.Column('pending_prompt_expires_at', sa.DATETIME(), nullable=True),
    sa.Column('last_prompt_fingerprint', sa.VARCHAR(), nullable=True),
    sa.Column('no_progress_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('last_learning_error', sa.VARCHAR(), nullable=True),
    sa.Column('work_scope', sa.VARCHAR(), server_default=sa.text("'session_goal'"), nullable=False),
    sa.Column('initial_goal_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('active_task_id', sa.VARCHAR(), nullable=True),
    sa.Column('active_task_title', sa.TEXT(), nullable=True),
    sa.Column('active_task_source', sa.VARCHAR(), nullable=True),
    sa.Column('active_task_fingerprint', sa.VARCHAR(), nullable=True),
    sa.Column('active_direction_revision', sa.INTEGER(), nullable=True),
    sa.Column('active_direction_fingerprint', sa.VARCHAR(), nullable=True),
    sa.Column('pending_task_delivery_fingerprint', sa.VARCHAR(), nullable=True),
    sa.Column('interaction_epoch', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_human_input_epoch', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_provider_hook_epoch', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_provider_hook_provider', sa.VARCHAR(), nullable=True),
    sa.Column('last_provider_hook_agent_session_id', sa.VARCHAR(), nullable=True),
    sa.Column('last_human_input_boot_ticks', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_hook_peer_pid', sa.INTEGER(), nullable=True),
    sa.Column('last_hook_peer_start_ticks', sa.INTEGER(), nullable=True),
    sa.Column('last_hook_provider_pid', sa.INTEGER(), nullable=True),
    sa.Column('last_hook_provider_start_ticks', sa.INTEGER(), nullable=True),
    sa.Column('last_hook_event_fingerprint', sa.VARCHAR(), nullable=True),
    sa.CheckConstraint("mode IN ('off', 'learn', 'active')", name=op.f('ck_session_automations_mode')),
    sa.CheckConstraint("state IN ('idle', 'observing', 'thinking', 'countdown', 'sending', 'waiting', 'paused', 'blocked', 'error')", name=op.f('ck_session_automations_state')),
    sa.CheckConstraint("work_scope IN ('session_goal', 'project_queue', 'direction_queue')", name=op.f('ck_session_automations_work_scope')),
    sa.CheckConstraint('max_failures BETWEEN 1 AND 10', name=op.f('ck_session_automations_max_failures')),
    sa.CheckConstraint('max_minutes BETWEEN 1 AND 1440', name=op.f('ck_session_automations_max_minutes')),
    sa.CheckConstraint('max_turns BETWEEN 1 AND 100', name=op.f('ck_session_automations_max_turns')),
    sa.CheckConstraint('send_delay_seconds BETWEEN 3 AND 30', name=op.f('ck_session_automations_send_delay')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_automations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_session_automations_tmux_identity'), ['tmux_server_id', 'tmux_session_id'], unique=1)
        batch_op.create_index(batch_op.f('uq_session_automations_project_session'), ['project_id', 'session_name'], unique=1)
        batch_op.create_index(batch_op.f('ix_session_automations_active_task_id'), ['active_task_id'], unique=False)

    op.create_table('project_direction_events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('revision', sa.INTEGER(), nullable=False),
    sa.Column('kind', sa.VARCHAR(), nullable=False),
    sa.Column('actor', sa.VARCHAR(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('snapshot_json', sa.TEXT(), nullable=False),
    sa.Column('snapshot_hash', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.CheckConstraint("kind IN ('draft_saved', 'approved', 'completed', 'cancelled', 'superseded')", name=op.f('ck_project_direction_event_kind')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_direction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_direction_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_direction_events_project_created'), ['project_id', 'created_at'], unique=False)

    op.create_table('task_proposals',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('proposal_key', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('execution_prompt', sa.TEXT(), nullable=False),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text("'4'"), nullable=False),
    sa.Column('desired_outcome', sa.TEXT(), nullable=False),
    sa.Column('risk_level', sa.VARCHAR(), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('acceptance_checks_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('required_skills_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('rationale', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'proposed'"), nullable=False),
    sa.Column('revision', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('last_source_event_key', sa.VARCHAR(), nullable=False),
    sa.Column('context_fingerprint', sa.VARCHAR(), nullable=False),
    sa.Column('approved_task_id', sa.VARCHAR(), nullable=True),
    sa.Column('decided_by', sa.VARCHAR(), nullable=True),
    sa.Column('decided_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('observed_task_id', sa.TEXT(), nullable=True),
    sa.Column('observed_automation_id', sa.TEXT(), nullable=True),
    sa.Column('observed_session_name', sa.TEXT(), nullable=True),
    sa.Column('observed_executor_binding_json', sa.TEXT(), nullable=True),
    sa.Column('observed_head_event_id', sa.TEXT(), nullable=True),
    sa.Column('observed_head_snapshot_hash', sa.TEXT(), nullable=True),
    sa.Column('observed_checkpoint_sha256', sa.TEXT(), nullable=True),
    sa.Column('observed_task_scope_sha256', sa.TEXT(), nullable=True),
    sa.Column('observed_release_authority_json', sa.TEXT(), nullable=True),
    sa.Column('observed_release_authority_sha256', sa.TEXT(), nullable=True),
    sa.Column('observed_projection_sha256', sa.TEXT(), nullable=True),
    sa.Column('observed_head_sequence', sa.INTEGER(), nullable=True),
    sa.Column('observed_released', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('observed_task_deleted', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('work_type', sa.VARCHAR(), server_default=sa.text("'maintenance'"), nullable=False),
    sa.Column('evidence_basis', sa.VARCHAR(), server_default=sa.text("'source_gap'"), nullable=False),
    sa.Column('evidence_summary', sa.TEXT(), server_default=sa.text("'Legacy learned proposal.'"), nullable=False),
    sa.Column('why_now', sa.TEXT(), server_default=sa.text("'Preserved from the current learned plan.'"), nullable=False),
    sa.Column('confidence', sa.INTEGER(), server_default=sa.text("'50'"), nullable=False),
    sa.Column('depends_on_proposal_keys_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_task_proposals_risk')),
    sa.CheckConstraint("status IN ('proposed', 'approved', 'rejected', 'superseded')", name=op.f('ck_task_proposals_status')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'proposal_key', name=op.f('uq_task_proposals_project_key'))
    )
    with op.batch_alter_table('task_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_proposals_project_status'), ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_proposals_observed_task'), ['observed_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_proposals_observed_session'), ['project_id', 'observed_session_name', 'observed_released'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_proposals_observed_automation'), ['project_id', 'observed_automation_id', 'observed_released'], unique=False)

    # ### end Alembic commands ###
