"""add missing serial_queue_id indexes

Revision ID: 6431220ddcf5
Revises: e9250b224a88
Create Date: 2026-08-08 11:24:05.256845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6431220ddcf5'
down_revision: Union[str, Sequence[str], None] = 'e9250b224a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _inspector():
    """Reflect the database this migration is running against."""
    return sa.inspect(op.get_bind())


def upgrade() -> None:
    """Create the two indexes declared in models.py but absent from older databases.

    Idempotent on purpose. The baseline revision was autogenerated from
    models.py, so it ALREADY creates both indexes — a freshly-migrated database
    reaches this revision with them in place and a bare create_index would fail
    with "index already exists".

    A pre-Alembic database is the case this exists for. It was built by
    create_all before `index=True` was added to these columns, and the old
    hand-rolled ADD COLUMN block could not create an index, so it has the
    columns and neither index. Stamping it at baseline asserts a schema it does
    not quite have; this revision closes that specific gap.
    """
    existing = {index["name"] for index in _inspector().get_indexes("projects")}
    if "ix_projects_serial_queue_id" not in existing:
        with op.batch_alter_table("projects", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_projects_serial_queue_id"),
                ["serial_queue_id"],
                unique=False,
            )

    existing = {index["name"] for index in _inspector().get_indexes("task_workflows")}
    if "ix_task_workflows_serial_queue_id" not in existing:
        with op.batch_alter_table("task_workflows", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_task_workflows_serial_queue_id"),
                ["serial_queue_id"],
                unique=False,
            )


def downgrade() -> None:
    """Drop both indexes if present."""
    for table, index in (
        ("task_workflows", "ix_task_workflows_serial_queue_id"),
        ("projects", "ix_projects_serial_queue_id"),
    ):
        existing = {item["name"] for item in _inspector().get_indexes(table)}
        if index in existing:
            with op.batch_alter_table(table, schema=None) as batch_op:
                batch_op.drop_index(batch_op.f(index))
