"""fleet memory and lanes

Revision ID: 9324cf29e61e
Revises: 3f7e985b6a91
Create Date: 2026-09-23 21:39:27.521291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9324cf29e61e'
down_revision: Union[str, Sequence[str], None] = '3f7e985b6a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ADDED_COLUMNS = {
    'fleet_attempts': [
        sa.Column('lane', sa.String(), server_default='interactive', nullable=False),
        sa.Column('container_name', sa.String(), nullable=True),
    ],
    'fleet_missions': [sa.Column('brain_context', sa.Text(), nullable=True)],
    'fleet_tasks': [sa.Column('lane', sa.String(), server_default='interactive', nullable=False)],
}


def upgrade() -> None:
    """Upgrade schema. Guarded: startup's create_all may have created these already."""
    bind = op.get_bind()
    if 'fleet_lessons' not in set(sa.inspect(bind).get_table_names()):
        op.create_table('fleet_lessons',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('project_id', sa.String(), nullable=False),
        sa.Column('repo_path', sa.Text(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('source', sa.String(), server_default='lead', nullable=False),
        sa.Column('status', sa.String(), server_default='proposed', nullable=False),
        sa.Column('mission_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('proposed', 'active', 'retired')", name='ck_fleet_lessons_status'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('fleet_lessons', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_fleet_lessons_project_id'), ['project_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_fleet_lessons_repo_path'), ['repo_path'], unique=False)
    for table, columns in _ADDED_COLUMNS.items():
        existing = {c["name"] for c in sa.inspect(bind).get_columns(table)}
        missing = [column for column in columns if column.name not in existing]
        if missing:
            with op.batch_alter_table(table, schema=None) as batch_op:
                for column in missing:
                    batch_op.add_column(column)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_tasks', schema=None) as batch_op:
        batch_op.drop_column('lane')

    with op.batch_alter_table('fleet_missions', schema=None) as batch_op:
        batch_op.drop_column('brain_context')

    with op.batch_alter_table('fleet_attempts', schema=None) as batch_op:
        batch_op.drop_column('container_name')
        batch_op.drop_column('lane')

    with op.batch_alter_table('fleet_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_lessons_repo_path'))
        batch_op.drop_index(batch_op.f('ix_fleet_lessons_project_id'))

    op.drop_table('fleet_lessons')
    # ### end Alembic commands ###
