"""fleet autonomy hardening: usage, policy, watchdog and review state on attempts

Revision ID: b0bd84338cc5
Revises: 55f6afddd80f
Create Date: 2026-09-23 20:20:42.936316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bd84338cc5'
down_revision: Union[str, Sequence[str], None] = '55f6afddd80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ADDED_COLUMNS = {
    'fleet_attempts': [
        sa.Column('transcript_path', sa.Text(), nullable=True),
        sa.Column('model', sa.String(), nullable=True),
        sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
        sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
        sa.Column('tokens_cache', sa.Integer(), server_default='0', nullable=False),
        sa.Column('cost_usd', sa.Float(), server_default='0', nullable=False),
        sa.Column('wrapup_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('denials', sa.Integer(), server_default='0', nullable=False),
        sa.Column('consecutive_denials', sa.Integer(), server_default='0', nullable=False),
        sa.Column('screen_hash', sa.String(), nullable=True),
        sa.Column('screen_changed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('stuck_nudges', sa.Integer(), server_default='0', nullable=False),
        sa.Column('last_commit_sha', sa.String(), nullable=True),
        sa.Column('turns_since_commit', sa.Integer(), server_default='0', nullable=False),
        sa.Column('review_verdict', sa.String(), nullable=True),
        sa.Column('review_json', sa.Text(), nullable=True),
    ],
}


def upgrade() -> None:
    """Upgrade schema. Guarded: create_all may already have added these columns."""
    for table, columns in _ADDED_COLUMNS.items():
        existing = {c["name"] for c in sa.inspect(op.get_bind()).get_columns(table)}
        missing = [column for column in columns if column.name not in existing]
        if missing:
            with op.batch_alter_table(table, schema=None) as batch_op:
                for column in missing:
                    batch_op.add_column(column)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_attempts', schema=None) as batch_op:
        batch_op.drop_column('review_json')
        batch_op.drop_column('review_verdict')
        batch_op.drop_column('turns_since_commit')
        batch_op.drop_column('last_commit_sha')
        batch_op.drop_column('stuck_nudges')
        batch_op.drop_column('screen_changed_at')
        batch_op.drop_column('screen_hash')
        batch_op.drop_column('consecutive_denials')
        batch_op.drop_column('denials')
        batch_op.drop_column('wrapup_sent_at')
        batch_op.drop_column('cost_usd')
        batch_op.drop_column('tokens_cache')
        batch_op.drop_column('tokens_out')
        batch_op.drop_column('tokens_in')
        batch_op.drop_column('model')
        batch_op.drop_column('transcript_path')

    # ### end Alembic commands ###
