"""baseline schema

Revision ID: e9250b224a88
Revises: 
Create Date: 2026-08-08 11:23:17.043659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9250b224a88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('is_inbox', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('serial_queue_id', sa.String(), nullable=True),
    sa.Column('serial_queue_status', sa.String(), server_default='idle', nullable=False),
    sa.Column('serial_queue_session_name', sa.String(), nullable=True),
    sa.Column('serial_queue_error', sa.Text(), nullable=True),
    sa.Column('serial_queue_created_at', sa.DateTime(), nullable=True),
    sa.Column('serial_queue_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_serial_queue_id'), ['serial_queue_id'], unique=False)

    op.create_table('research_bindings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_bindings_instance_id'), ['instance_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_research_bindings_project_id'), ['project_id'], unique=True)

    op.create_table('sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_collapsed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_labels',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('label_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'label_id')
    )
    op.create_table('task_workflows',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('research_status', sa.String(), nullable=False),
    sa.Column('launch_error', sa.Text(), nullable=True),
    sa.Column('research_brief', sa.Text(), nullable=False),
    sa.Column('prompt_sent_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('research_completed_at', sa.DateTime(), nullable=True),
    sa.Column('placement_kind', sa.String(), nullable=True),
    sa.Column('placement_project_id', sa.String(), nullable=True),
    sa.Column('placement_project_name', sa.String(), nullable=True),
    sa.Column('placement_workspace_path', sa.Text(), nullable=True),
    sa.Column('placement_reason', sa.Text(), nullable=True),
    sa.Column('placement_confidence', sa.Integer(), nullable=True),
    sa.Column('placement_generated_at', sa.DateTime(), nullable=True),
    sa.Column('source_project_id', sa.String(), nullable=True),
    sa.Column('cleanup_status', sa.String(), server_default='not_applicable', nullable=False),
    sa.Column('cleanup_error', sa.Text(), nullable=True),
    sa.Column('cleanup_archive_path', sa.Text(), nullable=True),
    sa.Column('cleanup_completed_at', sa.DateTime(), nullable=True),
    sa.Column('serial_queue_id', sa.String(), nullable=True),
    sa.Column('serial_queue_position', sa.Integer(), nullable=True),
    sa.Column('serial_queue_status', sa.String(), server_default='not_queued', nullable=False),
    sa.Column('serial_queue_error', sa.Text(), nullable=True),
    sa.Column('serial_queue_enqueued_at', sa.DateTime(), nullable=True),
    sa.Column('serial_queue_started_at', sa.DateTime(), nullable=True),
    sa.Column('serial_queue_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('session_name')
    )
    with op.batch_alter_table('task_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_workflows_serial_queue_id'), ['serial_queue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_workflows_serial_queue_id'))

    op.drop_table('task_workflows')
    op.drop_table('task_labels')
    op.drop_table('tasks')
    op.drop_table('sections')
    with op.batch_alter_table('research_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_bindings_project_id'))
        batch_op.drop_index(batch_op.f('ix_research_bindings_instance_id'))

    op.drop_table('research_bindings')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_serial_queue_id'))

    op.drop_table('projects')
    op.drop_table('labels')
    # ### end Alembic commands ###
